# Generated by Django 4.2.5 on 2023-10-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockADS', '0002_categorias_remove_products_size_products_caregory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
